apiVersion: deployments.plural.sh/v1alpha1
kind: GitRepository
metadata:
  name: lua-python-test
spec:
  # Cluster-scoped. Only spec.url is required.
  # SSH URLs also need spec.connectionRef or spec.credentialsRef.
  url: https://github.com/zreigz/lua-python-test
